services:
  mongo:
    image: mongo:5.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ./express
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=supersecretdevkey
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
    working_dir: /usr/src/app
    command: ["npm", "start"]
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:3000
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - app

volumes:
  mongo_data:
